import DecentralizedIcon from '@/components/icons/DecentralizedIcon';
import GrowthIcon from '@/components/icons/GrowthIcon';
import LaunchIcon from '@/components/icons/LaunchIcon';
import LimitlessIcon from '@/components/icons/LimitlessIcon';

export const ourMissionAccordionData = [
    {
        title: 'Profitability and Growth',
        content: `At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.`,
        Icon: GrowthIcon,
    },
    {
        title: 'Transparent & Fair Decentralized Earnings',
        content: `The key element of our proposal is the continuous access to distributed and decentralized earnings generated by AI tools that we provide through their creation or investment in them. This decentralized structure ensures greater transparency and fairness to all participants in the Creon ecosystem.`,
        Icon: DecentralizedIcon,
    },
    {
        title: 'Launching the future',
        content: `What's more, Creon is pioneering in offering the first known opportunity to acquire allocations in tokenised AI projects through our Creon Launchpad platform. This gives investors a unique chance for early engagement in the most promising AI projects, opening the door to potentially high returns.`,
        Icon: LaunchIcon,
    },
    {
        title: 'Limitless Possibilities of AI & Crypto',
        content: `The possibilities offered by the integration of AI and cryptocurrencies are limitless, and we're just beginning to explore them. As pioneers, our journey into uncharted territory is fraught with challenges, but the rewards promise to be equally extraordinary. Creon isn’t just about profiting from technological innovation; it's about being part of the process that brings these innovations to life.`,
        Icon: LimitlessIcon,
    },
];
